server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/photoapp}

app:
  jwt:
    secret: ${JWT_SECRET:changeme-in-production-min-256-bits-required-here}
    expiration-ms: 86400000       # 24h
    refresh-expiration-ms: 2592000000  # 30 jours
  encryption:
    key: ${ENCRYPTION_KEY:changeme-32-bytes-key-for-aes256}
  cors:
    allowed-origin: ${FRONTEND_URL:http://localhost:4200}
  upload:
    max-file-size-mb: 20

logging:
  level:
    com.photoapp: DEBUG
    org.springframework.security: INFO
